### PR TITLE
Renames logger package to rslog

### PR DESCRIPTION
**Pull request by eduardocfalcao**
This PR attempts to rename the `logger` package to `rslog`.

We thought it can good for the systems that use this library and have an internal package called logger. 
It happened with us on Connect, and renaming this package makes sense for us.

### CODE REVIEW

**Review by aronatkins — APPROVED** [review]
At some point, we'll want to think about versioning the library; this type of change would require a major version change.

**Review by marcosnav — APPROVED** [review]
LGTM :)

**Comment by eduardocfalcao** [comment]
> At some point, we'll want to think about versioning the library; this type of change would require a major version change.

@aronatkins 
Yup! you totally right. But at the moment, we are good following with this. But we should address this soon.

**Comment by jonyoder** [comment]
@aronatkins @eduardocfalcao we already have basic versioning in place. Currently we're simply pushing a tag to bump the version, and then you can constrain the version in your `go.mod` as necessary. See the releases page for the current prereleases.

**Review by jonyoder — APPROVED** [review]

**Pull request merged**
